#!/usr/bin/env bash
# Lista de variáveis de produção gravadas no backup completo (.env.prod-backup).
# Fonte: .env.production.example + secrets operacionais.

# shellcheck disable=SC2034
PROD_ENV_KEYS=(
  DOMAIN
  ACME_EMAIL
  NEXT_PUBLIC_API_URL
  FRONTEND_PUBLIC_URL
  NEXT_PUBLIC_PAYMENT_PROVIDER
  NEXT_PUBLIC_LOGO_URL
  NEXT_PUBLIC_SOCIAL_INSTAGRAM_URL
  NEXT_PUBLIC_SOCIAL_WHATSAPP_URL
  NEXT_PUBLIC_EMAIL_CONTATO
  NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY
  GOOGLE_OAUTH_CLIENT_ID
  NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID
  POSTGRES_PASSWORD
  PAYMENT_PROVIDER
  ASAAS_API_KEY
  ASAAS_WEBHOOK_TOKEN
  ASAAS_ENVIRONMENT
  ASAAS_DISABLED
  ASAAS_PLATFORM_WALLET_ID
  ASAAS_CREATE_SUBACCOUNT_ON_REGISTER
  ASAAS_ALLOW_MANUAL_WALLET
  ASAAS_ONBOARDING_MODE
  SECRET_KEY
  PLATFORM_ADMIN_API_KEY
  EMAIL_SERVER
  EMAIL_PORT
  EMAIL_USER
  EMAIL_PASSWORD
  EMAIL_FROM_NAME
  EMAIL_USE_TLS
  REDIS_URL
  RATE_LIMIT_USE_REDIS
  TICKET_EMAIL_USE_REDIS
  TICKET_EMAIL_MAX_ATTEMPTS
  CORS_ORIGINS
  TRUST_FORWARDED_HEADERS
  ENVIRONMENT
  DEBUG
  MARKETING_WHATSAPP_WEBHOOK_URL
  MARKETING_WHATSAPP_WEBHOOK_TOKEN
  BACKUP_OFFSITE_TARGET
)

# Variáveis mínimas obrigatórias para considerar o backup válido.
# shellcheck disable=SC2034
PROD_ENV_REQUIRED_KEYS=(
  DOMAIN
  POSTGRES_PASSWORD
  SECRET_KEY
  PLATFORM_ADMIN_API_KEY
  PAYMENT_PROVIDER
  ASAAS_API_KEY
  ASAAS_WEBHOOK_TOKEN
  ASAAS_PLATFORM_WALLET_ID
  EMAIL_USER
  EMAIL_PASSWORD
  CORS_ORIGINS
)
